version: "3"

services:
  eureka:
    build: ./eureka-server
    ports:
      - 8761:8761

  user-service:
    build: ./user-service
    ports:
      - 9098:9098

  zuulserver:
    build: ./zuul-server
    ports:
      - 9090:9090

  product-service:
    build: ./product-service
    ports:
      - 9099:9099